apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
    tier: backend
spec:
  serviceAccountName: myapp-service-account
  containers:
    - image: ulisesregistry.azurecr.io/myapp:1.6
      name: myapp
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
