apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-05-20T16:59:49Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: myapp
    tier: backend
  name: myapp
  namespace: default
  resourceVersion: "499021"
  uid: f0cd6ddc-c012-45e7-8159-cec5f1663cf0
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.180.162
  clusterIPs:
  - 10.0.180.162
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31105
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp
    tier: backend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.245.12.175
