apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
    - image: ulisesregistry.azurecr.io/myapp:1.0
      name: myapp
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
